# Numpy 

In [5]:
#creating a simple array in numpy

import numpy as np
a = np.array([1,2,3,4])

print(a)
print(np.arange(10))
a

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4])

In [7]:
l = range(10000)
%timeit [i**2 for i in l]

a = np.arange(10000)
%timeit a**2

4.12 ms ± 64.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
9.05 µs ± 268 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
a = np.array([1,3,4]) ## 1-D array (vector)
len(a)



3

In [14]:
b = np.array([[1,2,3], [3,2,3]]) #2-D array (matrix)
print(b)
b.shape
b

[[1 2 3]
 [3 2 3]]


array([[1, 2, 3],
       [3, 2, 3]])

In [17]:
c = np.array([[[0,1], [1,2]], [[2,3],[5,6]]]) # 3_d array( Tensor)
print(c)
print(c.dtype)

[[[0 1]
  [1 2]]

 [[2 3]
  [5 6]]]
int32


# Numerical Operation on 'NUMPY'



In [20]:
#basic scalar operation
a = np.array([1,2,3,4,5])
a + 1

array([2, 3, 4, 5, 6])

In [25]:
c = np.diag([1,2,3,4,5])
print(c*c)

print('Same output in below case also:')
print(c.dot(c))


[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
Same output in below case also:
[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]


In [28]:
#comparison

a = np.array([1,2,3,4,5])
b = np.array([2,1,3,4,5])
a == b
# np.array_equal(a,b)

array([False, False,  True,  True,  True])

In [34]:
a = np.arange(10)
print(a)
np.exp(a)



[0 1 2 3 4 5 6 7 8 9]


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [37]:
a = np.array([2,3,1])
print(np.sum(a))

x = np.array([[1, 1], [2, 2]])
x.sum(axis=0) # sum along column
#x.sum(axis=1) #sum along rows

6


array([3, 3])

In [42]:
a = np.array([1, 34, 54, 2])
#a.min()
#a.max()
#a.argmin()
a.argmax()

2

In [44]:
x = np.zeros((3,3))
np.any(x != 0)

False

In [46]:
a = np.array([1, 4, 3])
b = np.array([2, 3, 4])
print(a <= b)
(a<=b).all()

[ True False  True]


False

In [53]:
x = np.array([2, 1, 4, 2,])
print(x.mean())
print(np.median(x))
print(x.std())

y = np.array([[1,2,3], [4,5,6]])
print(y)
np.median(y, axis=1)

2.25
2.0
1.0897247358851685
[[1 2 3]
 [4 5 6]]


array([2., 5.])

In [56]:
a = np.array([[1,2,3], [4,5,6]])
print(a)
a.ravel()
print(a.T)
a.T.ravel()

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


array([1, 4, 2, 5, 3, 6])

In [57]:
print(a)
b = a.ravel()
print(b)
b = b.reshape((3, 2))
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [58]:
a = np.array([[5,3], [2,3]])
print(a)
b = np.sort(a, axis=1)

j = np.argsort(a)
print(j)

[[5 3]
 [2 3]]
[[1 0]
 [0 1]]
