# Numpy 

In [5]:
#creating a simple array in numpy

import numpy as np
a = np.array([1,2,3,4])

print(a)
print(np.arange(10))
a

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4])

In [7]:
l = range(10000)
%timeit [i**2 for i in l]

a = np.arange(10000)
%timeit a**2

4.12 ms ± 64.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
9.05 µs ± 268 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
a = np.array([1,3,4]) ## 1-D array (vector)
len(a)



3

In [14]:
b = np.array([[1,2,3], [3,2,3]]) #2-D array (matrix)
print(b)
b.shape
b

[[1 2 3]
 [3 2 3]]


array([[1, 2, 3],
       [3, 2, 3]])

In [17]:
c = np.array([[[0,1], [1,2]], [[2,3],[5,6]]]) # 3_d array( Tensor)
print(c)
print(c.dtype)

[[[0 1]
  [1 2]]

 [[2 3]
  [5 6]]]
int32


# Numerical Operation on 'NUMPY'



In [20]:
#basic scalar operation
a = np.array([1,2,3,4,5])
a + 1

array([2, 3, 4, 5, 6])